[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_treasury = "GU1B8EVCww9jiAGu7jE4YaEnYa6W1edB7KG3oprVgPyu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/deok/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
